/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Entity.KhachHang;
import Repository.NhanVienRepository;
import Response.NhanVienResponse;
import static java.nio.file.Files.list;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;

public class ViewNhanVien extends javax.swing.JPanel {

    private NhanVienResponse nvre;
    private NhanVienRepository nvrepo;
    private ArrayList<NhanVienResponse> list_nv = new ArrayList<>();
    private DefaultComboBoxModel dcbm;
    private DefaultTableModel dtmkh;

    public ViewNhanVien() {
        initComponents();
        nvre = new NhanVienResponse();
        nvrepo = new NhanVienRepository();
        list_nv = nvrepo.getAll();
        dtmkh = (DefaultTableModel) tblNhanVien.getModel();
        fillTable(list_nv);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        lblHoTen = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jdaNgayTao = new com.toedter.calendar.JDateChooser();
        txtHoTen = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        lblNgayTao1 = new javax.swing.JLabel();
        jdaNgaySua = new com.toedter.calendar.JDateChooser();
        txtMaNV = new javax.swing.JTextField();
        lblHoTen1 = new javax.swing.JLabel();
        txtmatKhau = new javax.swing.JTextField();
        lblHoTen2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblSoDienThoai1 = new javax.swing.JLabel();
        lblGioiTinh1 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 243, 234));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        jPanel3.setBackground(new java.awt.Color(128, 203, 196));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 600));

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(255, 253, 246));
        lblHoTen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHoTen.setText("Họ và tên");

        lblSoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSoDienThoai.setForeground(new java.awt.Color(255, 253, 246));
        lblSoDienThoai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSoDienThoai.setText("Số điện thoại");

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(255, 253, 246));
        lblGioiTinh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGioiTinh.setText("Giới tính");

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(255, 253, 246));
        lblDiaChi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiaChi.setText("Địa chỉ");

        lblNgayTao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNgayTao.setForeground(new java.awt.Color(255, 253, 246));
        lblNgayTao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNgayTao.setText("Ngày tạo");

        rdoNam.setBackground(new java.awt.Color(128, 203, 196));
        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rdoNam.setForeground(new java.awt.Color(255, 253, 246));
        rdoNam.setText("Nam");
        rdoNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNamActionPerformed(evt);
            }
        });

        rdoNu.setBackground(new java.awt.Color(128, 203, 196));
        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rdoNu.setForeground(new java.awt.Color(255, 253, 246));
        rdoNu.setText("Nữ");
        rdoNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNuActionPerformed(evt);
            }
        });

        jdaNgayTao.setDateFormatString("dd/MM/yyyy");
        jdaNgayTao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDiaChi.setColumns(20);
        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiaChi.setRows(5);
        jScrollPane1.setViewportView(txtDiaChi);

        lblNgayTao1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNgayTao1.setForeground(new java.awt.Color(255, 253, 246));
        lblNgayTao1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNgayTao1.setText("Ngày Sửa");

        jdaNgaySua.setDateFormatString("dd/MM/yyyy");
        jdaNgaySua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMaNV.setEditable(false);
        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        lblHoTen1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHoTen1.setForeground(new java.awt.Color(255, 253, 246));
        lblHoTen1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHoTen1.setText("Mã");

        txtmatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblHoTen2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHoTen2.setForeground(new java.awt.Color(255, 253, 246));
        lblHoTen2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHoTen2.setText("Mật Khẩu");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblSoDienThoai1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSoDienThoai1.setForeground(new java.awt.Color(255, 253, 246));
        lblSoDienThoai1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSoDienThoai1.setText("Email");

        lblGioiTinh1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblGioiTinh1.setForeground(new java.awt.Color(255, 253, 246));
        lblGioiTinh1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGioiTinh1.setText("Chức Vụ");

        txtChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHoTen1)
                                    .addComponent(lblHoTen)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rdoNam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoNu))
                                    .addComponent(lblGioiTinh)
                                    .addComponent(lblGioiTinh1))
                                .addGap(184, 184, 184)))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNgayTao1)
                            .addComponent(lblNgayTao)
                            .addComponent(lblHoTen2)
                            .addComponent(lblSoDienThoai)
                            .addComponent(txtMaNV)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(txtmatKhau)
                            .addComponent(txtSoDienThoai)
                            .addComponent(lblSoDienThoai1)
                            .addComponent(txtEmail)
                            .addComponent(jdaNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jdaNgaySua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiaChi)
                            .addComponent(txtChucVu))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblGioiTinh, lblNgayTao, lblSoDienThoai});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jdaNgayTao, txtHoTen, txtSoDienThoai});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblHoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHoTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoNam)
                            .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGioiTinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblSoDienThoai1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdaNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNgayTao1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdaNgaySua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDiaChi, lblGioiTinh, lblHoTen, lblNgayTao, lblSoDienThoai});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jdaNgayTao, txtHoTen, txtSoDienThoai});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rdoNam, rdoNu});

        jPanel4.setBackground(new java.awt.Color(128, 203, 196));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 600));

        tblNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Họ tên", "Địa chỉ", "Mật khẩu", "Giới tính", "Email", "SĐT", "chức vụ", "Ngày tạo", "Ngày Sửa", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setGridColor(new java.awt.Color(128, 203, 196));
        tblNhanVien.setRowHeight(30);
        tblNhanVien.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhanVien);

        lblTimKiem.setBackground(new java.awt.Color(255, 253, 246));
        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(255, 253, 246));
        lblTimKiem.setText("Tìm kiếm");

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiem.setToolTipText("");
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addGap(33, 33, 33)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSua)
                    .addComponent(btnMoi)
                    .addComponent(btnThem))
                .addGap(293, 293, 293))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMoi, btnSua, btnThem});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int selectedRow = tblNhanVien.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần sửa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        NhanVienResponse kh = nvrepo.getAll().get(selectedRow);

        // Lấy dữ liệu từ form
        String hoTen = txtHoTen.getText();
        String diaChi = txtDiaChi.getText();
        String matKhau = txtmatKhau.getText();
        boolean gioiTinh = rdoNam.isSelected();
        String email = txtEmail.getText();
        String soDienThoai = txtSoDienThoai.getText();
        String chucVu = txtChucVu.getText();
        Date ngayTao = jdaNgayTao.getDate();
        Date ngaySua = jdaNgaySua.getDate();

        kh.setTenNhanVien(hoTen);
        kh.setDiaChi(diaChi);
        kh.setMatKhau(matKhau);
        kh.setGioiTinh(gioiTinh);
        kh.setEmail(email);
        kh.setSoDienThoai(soDienThoai);
        kh.setChucVu(chucVu);
        kh.setNgayTao(ngayTao);
        kh.setNgaySua(ngaySua);
        boolean success = nvrepo.sua(kh.getId(), kh);

        if (success) {
            JOptionPane.showMessageDialog(this, "Cập nhật khách hàng thành công!");
            list_nv = nvrepo.getAll();
            fillTable(list_nv); // Cập nhật lại bảng
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
try {
            // Lấy dữ liệu từ form
            String hoTen = txtHoTen.getText().trim();
            String diaChi = txtDiaChi.getText().trim();
            String matKhau = txtmatKhau.getText().trim();
            Boolean gioiTinh = rdoNam.isSelected();
            String email = txtEmail.getText().trim();
            String soDienThoai = txtSoDienThoai.getText().trim();
            String chucVu = txtChucVu.getText().trim();
            Date ngayTao = (jdaNgayTao.getDate() != null) ? new Date(jdaNgayTao.getDate().getTime()) : null;
            Date ngaySua = (jdaNgaySua.getDate() != null) ? new Date(jdaNgaySua.getDate().getTime()) : null;
            int trangThai = 1;

            // Kiểm tra rỗng
            if (hoTen.isEmpty() || diaChi.isEmpty() || matKhau.isEmpty()
                    || email.isEmpty() || soDienThoai.isEmpty() || chucVu.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
                return;
            }

            // Kiểm tra định dạng
            if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
                JOptionPane.showMessageDialog(this, "Email không đúng định dạng.");
                return;
            }

            if (!soDienThoai.matches("^0\\d{9}$")) {
                JOptionPane.showMessageDialog(this, "Số điện thoại phải đủ 10 số và bắt đầu bằng 0.");
                return;
            }

            // Tạo đối tượng nhân viên
            NhanVienResponse kh = new NhanVienResponse();
            kh.setTenNhanVien(hoTen);
            kh.setDiaChi(diaChi);
            kh.setMatKhau(matKhau);
            kh.setGioiTinh(gioiTinh);
            kh.setEmail(email);
            kh.setSoDienThoai(soDienThoai);
            kh.setChucVu(chucVu);
            kh.setNgayTao(ngayTao);
            kh.setNgaySua(ngaySua);
            kh.setTrangThai(trangThai);

            // Gọi repo để thêm (không cần set mã nếu mã tự tăng)
            nvrepo.addNhanVien(kh);

            // Load lại danh sách từ database và đổ lại bảng
            list_nv = nvrepo.getAll();
            fillTable(list_nv);

            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm nhân viên.");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        txtHoTen.setText("");
        txtSoDienThoai.setText("");
        rdoNam.isSelected();
        jdaNgayTao.setDate(null);
        txtDiaChi.setText("");
        txtMaNV.setText("");
        txtmatKhau.setText("");
        txtEmail.setText("");
        jdaNgayTao.setDate(null);
        txtChucVu.setText("");
    }//GEN-LAST:event_btnMoiActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        int row = tblNhanVien.getSelectedRow();
        if (row == -1) {
            return;
        }
        NhanVienResponse kh = nvrepo.getAll().get(row);
        txtMaNV.setText(kh.getMaNhanVien());
        txtHoTen.setText(kh.getTenNhanVien());
        txtDiaChi.setText(kh.getDiaChi());
        txtmatKhau.setText(kh.getMatKhau());
        rdoNam.setSelected(kh.isGioiTinh());
        rdoNu.setSelected(!kh.isGioiTinh());
        txtEmail.setText(kh.getEmail());
        txtSoDienThoai.setText(kh.getSoDienThoai());
        txtChucVu.setText(kh.getChucVu());
        jdaNgaySua.setDate(kh.getNgaySua());
        jdaNgayTao.setDate(kh.getNgayTao());

    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        String keyword = txtTimKiem.getText().trim();
        ArrayList<NhanVienResponse> list_search = nvrepo.search(keyword, keyword, keyword);
        fillTable(list_search);
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void rdoNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNuActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void rdoNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdaNgaySua;
    private com.toedter.calendar.JDateChooser jdaNgayTao;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblGioiTinh1;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblHoTen1;
    private javax.swing.JLabel lblHoTen2;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblNgayTao1;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblSoDienThoai1;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtmatKhau;
    // End of variables declaration//GEN-END:variables

  private void fillTable(ArrayList<NhanVienResponse> list_nv) {
        dtmkh.setRowCount(0);
        int index = 1;
        for (NhanVienResponse nv : list_nv) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            dtmkh.addRow(new Object[]{
                index++,
                nv.getMaNhanVien(),
                nv.getTenNhanVien(),
                nv.getDiaChi(),
                nv.getMatKhau(),
                nv.isGioiTinh() ? "Nam" : "Nữ",
                nv.getEmail(),
                nv.getSoDienThoai(),
                nv.getChucVu(),
                nv.getNgayTao() != null ? sdf.format(nv.getNgayTao()) : "",
                nv.getNgaySua() != null ? sdf.format(nv.getNgaySua()) : "",
                nv.getTrangThai() == 1 ? "Hoạt động" : "không hoạt động"
            });
        }

    }

}
